/**
 * Contratos e cabeçalhos dos templates de importação (somente fictícios).
 */

export const IMPORT_ENTITY_TYPES = [
  "doctors",
  "facilities",
  "registrations",
  "links",
  "contacts",
  "evidences",
] as const;

export type ImportEntityType = (typeof IMPORT_ENTITY_TYPES)[number];

export const IMPORT_ENTITY_LABELS: Record<ImportEntityType, string> = {
  doctors: "Médicos",
  facilities: "Estabelecimentos",
  registrations: "Registros CRM/RQE",
  links: "Vínculos",
  contacts: "Contatos",
  evidences: "Evidências e fontes",
};

export const DOCTOR_IMPORT_HEADERS = [
  "full_name",
  "social_name",
  "classification",
  "confidence_score",
  "city",
  "state_uf",
  "biography",
  "declared_practice_area",
  "confirmed_practice_area",
  "practice_keywords",
  "graduation_institution",
  "graduation_year",
  "residency",
  "specialization",
  "fellowships",
  "masters_degree",
  "doctorate_degree",
  "professional_titles",
  "medical_societies",
  "is_sbhci_member",
  "lattes_url",
  "orcid",
  "notes",
  "source_code",
  "source_url",
  "captured_at",
] as const;

export const REGISTRATION_IMPORT_HEADERS = [
  "doctor_name",
  "registration_type",
  "number",
  "state_uf",
  "status",
  "inscription_type",
  "is_primary",
  "specialty_name",
  "rqe_area",
  "rqe_status",
  "consulted_at",
  "verified_at",
  "verification_status",
  "source_code",
  "source_url",
  "notes",
] as const;

export const FACILITY_IMPORT_HEADERS = [
  "legal_name",
  "trade_name",
  "cnes_code",
  "cnpj",
  "facility_type",
  "legal_nature",
  "ownership_type",
  "branch_type",
  "is_active",
  "address_zip",
  "address_street",
  "address_number",
  "address_complement",
  "address_district",
  "city",
  "state_uf",
  "ibge_city_code",
  "region",
  "latitude",
  "longitude",
  "phone",
  "email",
  "website",
  "hemodynamics_phone",
  "institutional_whatsapp",
  "hemodynamics_email",
  "secretary_contact",
  "service_manager_contact",
  "attends_sus",
  "attends_private",
  "attends_insurance",
  "has_hemodynamics",
  "has_catheterization_lab",
  "has_interventional_cardiology",
  "has_interventional_radiology",
  "has_interventional_neuroradiology",
  "is_24_hours",
  "has_emergency_service",
  "estimated_rooms",
  "estimated_equipment",
  "procedures",
  "service_notes",
  "source_code",
  "source_url",
  "last_service_confirmed_at",
] as const;

export const LINK_IMPORT_HEADERS = [
  "doctor_name",
  "doctor_crm",
  "doctor_crm_uf",
  "facility_cnes",
  "facility_name",
  "position",
  "function_title",
  "department",
  "practiced_specialty",
  "is_coordinator",
  "is_team_leader",
  "is_technical_responsible",
  "is_clinical_staff",
  "weekly_hours",
  "is_sus_link",
  "link_status",
  "start_date",
  "end_date",
  "confidence_score",
  "source_code",
  "source_url",
  "last_verified_at",
  "notes",
] as const;

export const CONTACT_IMPORT_HEADERS = [
  "doctor_crm",
  "doctor_crm_uf",
  "facility_cnes",
  "contact_type",
  "contact_value",
  "label",
  "is_institutional",
  "is_public",
  "is_primary",
  "accepts_contact",
  "do_not_contact",
  "contact_status",
  "source_origin",
  "source_code",
  "source_url",
  "collected_at",
  "verified_at",
  "notes",
] as const;

export const EVIDENCE_IMPORT_HEADERS = [
  "entity_type",
  "doctor_crm",
  "doctor_crm_uf",
  "facility_cnes",
  "title",
  "description",
  "url",
  "confirmed_field",
  "captured_value",
  "collected_at",
  "source_code",
  "source_url",
  "notes",
] as const;

export const TEMPLATE_HEADERS: Record<ImportEntityType, readonly string[]> = {
  doctors: DOCTOR_IMPORT_HEADERS,
  facilities: FACILITY_IMPORT_HEADERS,
  registrations: REGISTRATION_IMPORT_HEADERS,
  links: LINK_IMPORT_HEADERS,
  contacts: CONTACT_IMPORT_HEADERS,
  evidences: EVIDENCE_IMPORT_HEADERS,
};

/** Exemplos fictícios (uma linha) — nunca dados reais. */
export const TEMPLATE_EXAMPLE_ROWS: Record<ImportEntityType, Record<string, string>> = {
  doctors: {
    full_name: "Médico Demonstração Template 001",
    social_name: "",
    classification: "possivel_candidato",
    confidence_score: "20",
    city: "Belo Horizonte",
    state_uf: "MG",
    biography: "DADO FICTÍCIO",
    declared_practice_area: "Hemodinâmica",
    confirmed_practice_area: "",
    practice_keywords: "hemodinamica;dado-ficticio",
    graduation_institution: "Universidade Fictícia MG",
    graduation_year: "2010",
    residency: "Cardiologia fictícia",
    specialization: "",
    fellowships: "",
    masters_degree: "",
    doctorate_degree: "",
    professional_titles: "",
    medical_societies: "",
    is_sbhci_member: "false",
    lattes_url: "https://lattes.example.com/demo001",
    orcid: "0000-0002-1825-0097",
    notes: "DADO FICTÍCIO — template",
    source_code: "PLANILHA_INTERNA",
    source_url: "https://fonte.example.com/demo",
    captured_at: "2026-01-15",
  },
  facilities: {
    legal_name: "Hospital Demonstração Template BH",
    trade_name: "Hemo Demo BH",
    cnes_code: "9999001",
    cnpj: "00000000000191",
    facility_type: "Hospital",
    legal_nature: "Privada",
    ownership_type: "privado",
    branch_type: "unico",
    is_active: "true",
    address_zip: "30130100",
    address_street: "Rua Fictícia",
    address_number: "100",
    address_complement: "DADO FICTÍCIO",
    address_district: "Centro",
    city: "Belo Horizonte",
    state_uf: "MG",
    ibge_city_code: "3106200",
    region: "Sudeste",
    latitude: "-19.9167",
    longitude: "-43.9345",
    phone: "3130000001",
    email: "contato@hospital-demo.example.com",
    website: "https://hospital-demo.example.com",
    hemodynamics_phone: "3199000001",
    institutional_whatsapp: "3199000002",
    hemodynamics_email: "hemo@hospital-demo.example.com",
    secretary_contact: "secretaria@hospital-demo.example.com",
    service_manager_contact: "gestor@hospital-demo.example.com",
    attends_sus: "true",
    attends_private: "true",
    attends_insurance: "true",
    has_hemodynamics: "true",
    has_catheterization_lab: "true",
    has_interventional_cardiology: "true",
    has_interventional_radiology: "false",
    has_interventional_neuroradiology: "false",
    is_24_hours: "true",
    has_emergency_service: "true",
    estimated_rooms: "2",
    estimated_equipment: "2",
    procedures: "Cateterismo (fictício)",
    service_notes: "DADO FICTÍCIO",
    source_code: "CNES",
    source_url: "https://cnes.example.com/demo",
    last_service_confirmed_at: "2026-01-10",
  },
  registrations: {
    doctor_name: "Médico Demonstração Template 001",
    registration_type: "CRM",
    number: "900001",
    state_uf: "MG",
    status: "ativo",
    inscription_type: "principal",
    is_primary: "true",
    specialty_name: "",
    rqe_area: "",
    rqe_status: "",
    consulted_at: "2026-01-15",
    verified_at: "",
    verification_status: "nao_verificado",
    source_code: "CRM_ESTADUAL",
    source_url: "https://crm.example.com/demo",
    notes: "CRM FICTÍCIO — NÃO UTILIZAR",
  },
  links: {
    doctor_name: "Médico Demonstração Template 001",
    doctor_crm: "900001",
    doctor_crm_uf: "MG",
    facility_cnes: "9999001",
    facility_name: "Hospital Demonstração Template BH",
    position: "Médico",
    function_title: "Hemodinamicista",
    department: "Hemodinâmica",
    practiced_specialty: "Hemodinâmica",
    is_coordinator: "false",
    is_team_leader: "false",
    is_technical_responsible: "false",
    is_clinical_staff: "true",
    weekly_hours: "20",
    is_sus_link: "true",
    link_status: "ativo",
    start_date: "2024-01-01",
    end_date: "",
    confidence_score: "40",
    source_code: "SITE_INSTITUCIONAL",
    source_url: "https://hospital-demo.example.com/equipe",
    last_verified_at: "2026-01-15",
    notes: "DADO FICTÍCIO",
  },
  contacts: {
    doctor_crm: "900001",
    doctor_crm_uf: "MG",
    facility_cnes: "",
    contact_type: "email",
    contact_value: "medico001@example.com",
    label: "Profissional",
    is_institutional: "false",
    is_public: "true",
    is_primary: "true",
    accepts_contact: "true",
    do_not_contact: "false",
    contact_status: "nao_validado",
    source_origin: "planilha_interna",
    source_code: "PLANILHA_INTERNA",
    source_url: "https://fonte.example.com/contatos",
    collected_at: "2026-01-15",
    verified_at: "",
    notes: "DADO FICTÍCIO",
  },
  evidences: {
    entity_type: "doctor",
    doctor_crm: "900001",
    doctor_crm_uf: "MG",
    facility_cnes: "",
    title: "Evidência fictícia de template",
    description: "DADO FICTÍCIO",
    url: "https://evidencia-demo.example.com/1",
    confirmed_field: "full_name",
    captured_value: "Médico Demonstração Template 001",
    collected_at: "2026-01-15",
    source_code: "SITE_INSTITUCIONAL",
    source_url: "https://hospital-demo.example.com",
    notes: "DADO FICTÍCIO",
  },
};

export function buildTemplateCsv(entity: ImportEntityType): string {
  const headers = TEMPLATE_HEADERS[entity];
  const example = TEMPLATE_EXAMPLE_ROWS[entity];
  const escape = (value: string) => {
    if (/[",\n;]/.test(value)) return `"${value.replace(/"/g, '""')}"`;
    return value;
  };
  const headerLine = headers.join(",");
  const rowLine = headers.map((h) => escape(example[h] ?? "")).join(",");
  return `${headerLine}\n${rowLine}\n`;
}

export function autoMapColumns(
  fileHeaders: string[],
  entity: ImportEntityType,
): Record<string, string> {
  const expected = TEMPLATE_HEADERS[entity];
  const normalized = new Map(
    fileHeaders.map((h) => [h.trim().toLowerCase(), h]),
  );
  const mapping: Record<string, string> = {};
  for (const target of expected) {
    const source = normalized.get(target.toLowerCase());
    if (source) mapping[target] = source;
  }
  return mapping;
}
